[tool.poetry]
name = "test-task"
version = "0.1.0"
description = ""
authors = ["kiluzoldik <gakerchannel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
